export const KAKAO_TALK_API_URL = 'https://sens.apigw.ntruss.com/alimtalk/v2/services';
export const DEFAULT_COUNTRY_CODE = '+82';
export const DEFAULT_PLUS_FRIEND_ID = '@픽업해';

export const TEMPLATE_CODES = {
  SIGN_UP: 'SIGN_UP',
  NEW_SERVICE_REQUEST: 'NEW_SERVICE_REQUEST',
  MATCH_SUCCESS: 'MATCH_SUCCESS',
  COMPLETED_SERVICE: 'COMPLETED_SERVICE',
  NEW_MESSAGE: 'NEW_MESSAGE',
  AUTO_CLOSED: 'AUTO_CLOSED',
  CANCELED_SERVICE: 'CANCELED_SERVICE',
  START_SERVICE_MATCHING: 'START_SERVICE_MATCHING',
  NEW_APPLICATION: 'NEW_APPLICATION',
  CLASS_REMINDER: 'CLASS_REMINDER',
  REQUEST_CLASS_NOTE: 'REQUEST_CLASS_NOTE',
  COMPLETE_CLASS_NOTE: 'COMPLETE_CLASS_NOTE',
  REQUEST_REVIEW: 'REQUEST_REVIEW',
} as const; 